pipeline:
  build:
    image: node:9.3.0
    commands:
      - npm install
      - npm run build
    when:
      event: tag

  npm:
    image: plugins/npm
    secrets: [ npm_password ]
    username: sulliwane
    email: sulliwane@gmail.com
    when:
      event: tag

  publish:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      event: tag
