matrix:
  NODE_TAG:
    - 10
    - 8

pipeline:
  build:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      branch: [master, next]

  build_on_tag:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      ref: [refs/tags/v*]

  npm_v3:
    image: plugins/npm
    secrets: [npm_password]
    username: sulliwane
    email: sulliwane@gmail.com
    tag: latest
    when:
      ref: [refs/tags/v3*]
      matrix:
        NODE_TAG: 8

  dockerhub_v3:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      ref: [refs/tags/v3*]
      matrix:
        NODE_TAG: 8

services:
  ethereum:
    image: iexechub/poco-chain
    pull: true
