pipeline:
  publish:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      event: tag
