matrix:
  NODE_TAG:
    - 9
    - 8
    - 6

pipeline:
  build:
    image: node:${NODE_TAG}
    commands:
      - npm install
      - npm run build
      - npm -g install .
      - npm test
    when:
      event: tag

  npm:
    image: plugins/npm
    secrets: [ npm_password ]
    username: sulliwane
    email: sulliwane@gmail.com
    tag: next
    when:
      event: tag
      matrix:
        NODE_TAG: 6

  publish:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [ docker_username, docker_password ]
    tags:
      - next
      - ${DRONE_TAG##v}
    when:
      event: tag
      matrix:
        NODE_TAG: 6
