matrix:
  NODE_TAG:
    - 12
    - 10
    - 8

pipeline:
  build:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      branch: [master, next, v5-alpha]

  build_on_tag:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      ref: [refs/tags/v*]

  npm_v4:
    image: plugins/npm
    secrets: [npm_password]
    username: sulliwane
    email: sulliwane@gmail.com
    tag: latest
    when:
      ref: [refs/tags/v4*]
      matrix:
        NODE_TAG: 8

  dockerhub_v4:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      ref: [refs/tags/v4*]
      matrix:
        NODE_TAG: 8

  npm_v5-alpha:
    image: plugins/npm
    secrets: [npm_password]
    username: sulliwane
    email: sulliwane@gmail.com
    tag: alpha
    when:
      ref: [refs/tags/v5.0.0-alpha.*]
      matrix:
        NODE_TAG: 8

  dockerhub_v5-alpha:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [docker_username, docker_password]
    tags:
      - alpha
      - ${DRONE_TAG##v}
    when:
      ref: [refs/tags/v5.0.0-alpha.*]
      matrix:
        NODE_TAG: 8

services:
  token-chain:
    image: iexechub/poco-chaintest:v5.0.1-token
    pull: true
  native-chain:
    image: iexechub/poco-chaintest:v5.0.1-native
    pull: true
  token-chain-1s:
    image: iexechub/poco-chaintest:v5.0.1-token-1s
    pull: true
