matrix:
  NODE_TAG:
    - 10
    - 8

pipeline:
  build:
    image: node:${NODE_TAG}
    commands:
      - npm install
      - npm run build
      - npm -g install .
      - npm test
    when:
      branch: [v2, master, next]

  npm:
    image: plugins/npm
    secrets: [npm_password]
    username: sulliwane
    email: sulliwane@gmail.com
    when:
      ref: [refs/tags/v2*]
      matrix:
        NODE_TAG: 8

  dockerhub:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_TAG##v}
    when:
      ref: [refs/tags/v2*]
      matrix:
        NODE_TAG: 8
