matrix:
  NODE_TAG:
    - 10
    - 8

pipeline:
  build:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      branch: [master, next]

  build_on_tag:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      ref: [refs/tags/v*]

  npm_v4:
    image: plugins/npm
    secrets: [npm_password]
    username: sulliwane
    email: sulliwane@gmail.com
    tag: alpha
    when:
      ref: [refs/tags/v4.0.0-alpha.*]
      matrix:
        NODE_TAG: 8

services:
  ethereum:
    image: iexechub/poco-chaintest
    pull: true
