matrix:
  NODE_TAG:
    - 14
    - 12
    - 10

pipeline:
  build_node_10:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      matrix:
        NODE_TAG: 10

  build_on_tag:
    image: node:${NODE_TAG}
    pull: true
    commands:
      - node -v
      - npm -v
      - npm install
      - ./node_modules/.bin/babel --version
      - npm run build
      - npm -g install .
      - npm test
    when:
      ref: [refs/tags/v*]

  npm_v5:
    image: plugins/npm
    secrets: [npm_password]
    username: sulliwane
    email: sulliwane@gmail.com
    tag: latest
    when:
      ref: [refs/tags/v5*]
      matrix:
        NODE_TAG: 10

  dockerhub_v5:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      ref: [refs/tags/v5*]
      matrix:
        NODE_TAG: 10

services:
  token-chain:
    image: iexechub/poco-chaintest:5.3.0-alpha.2-token
    pull: true
  native-chain:
    image: iexechub/poco-chaintest:5.3.0-alpha.2-native
    pull: true
  token-chain-1s:
    image: iexechub/poco-chaintest:5.3.0-alpha.2-token-1s
    pull: true
