pipeline:
  publish:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [ docker_username, docker_password ]
    tags: [ ${DRONE_TAG}, latest ]
    when:
      event: tag
      branch: master
